# Generated by Django 3.2.16 on 2023-01-31 03:05

import core.models.User
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255, null=True)),
                ('phone', models.CharField(max_length=10, null=True)),
                ('password', models.CharField(max_length=255)),
                ('profile_image', models.ImageField(null=True, upload_to=core.models.User.profile_image_file_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField()),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'User',
            },
        ),
        migrations.CreateModel(
            name='ContentTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('content_types', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Content Type',
                'verbose_name_plural': 'Content Types',
                'db_table': 'ContentTypes',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfc', models.CharField(max_length=13, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255, null=True)),
                ('phone', models.CharField(max_length=10, null=True)),
                ('email', models.EmailField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'db_table': 'Customer',
            },
        ),
        migrations.CreateModel(
            name='DataType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Data Type',
                'verbose_name_plural': 'Data Types',
                'db_table': 'DataType',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.customer')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'db_table': 'Project',
            },
        ),
        migrations.CreateModel(
            name='UploadSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('size', models.IntegerField(choices=[('2MB', 2621440), ('5MB', 5242880), ('10MB', 10485760)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Upload Size',
                'verbose_name_plural': 'Upload Sizes',
                'db_table': 'UploadSize',
            },
        ),
        migrations.CreateModel(
            name='ProjectModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_static', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.project')),
            ],
            options={
                'verbose_name': 'Project Model',
                'verbose_name_plural': 'Project Models',
                'db_table': 'ProjectModel',
            },
        ),
        migrations.CreateModel(
            name='ModelField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('caption', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_required', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('data_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.datatype')),
                ('project_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.projectmodel')),
            ],
            options={
                'verbose_name': 'Model Field',
                'verbose_name_plural': 'Model Fields',
                'db_table': 'ModelField',
            },
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Maintenance',
                'verbose_name_plural': 'Maintenances',
                'db_table': 'Maintenance',
            },
        ),
        migrations.CreateModel(
            name='IntegerFieldConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_value', models.IntegerField(null=True)),
                ('max_value', models.IntegerField(null=True)),
                ('only_positive', models.BooleanField(default=False)),
                ('big_integer', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('model_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.modelfield')),
            ],
            options={
                'verbose_name': 'Integer Field Config',
                'verbose_name_plural': 'Integer Field Configs',
                'db_table': 'IntegerFieldConfig',
            },
        ),
        migrations.CreateModel(
            name='ForeignKeyFieldConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(choices=[('1', 'One to One'), ('2', 'One to Many'), ('3', 'Many to Many')], max_length=1)),
                ('on_delete', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('model_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.modelfield')),
            ],
            options={
                'verbose_name': 'Foreign Key Field Config',
                'verbose_name_plural': 'Foreign Key Field Configs',
                'db_table': 'ForeignKeyFieldConfig',
            },
        ),
        migrations.CreateModel(
            name='FloatFieldConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_value', models.FloatField(null=True)),
                ('max_value', models.FloatField(null=True)),
                ('max_digits', models.IntegerField(null=True)),
                ('decimal_places', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('model_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.modelfield')),
            ],
            options={
                'verbose_name': 'Float Field Config',
                'verbose_name_plural': 'Float Field Configs',
                'db_table': 'FloatFieldConfig',
            },
        ),
        migrations.CreateModel(
            name='FileFieldConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_to', models.CharField(max_length=255)),
                ('max_length', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('model_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.modelfield')),
                ('upload_size', models.ManyToManyField(related_name='file_field_config', to='core.UploadSize')),
            ],
            options={
                'verbose_name': 'File Field Config',
                'verbose_name_plural': 'File Field Configs',
                'db_table': 'FileFieldConfig',
            },
        ),
        migrations.CreateModel(
            name='DateFieldConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('date', 'Date'), ('datetime', 'Date Time'), ('time', 'Time')], max_length=255)),
                ('auto_now', models.BooleanField(default=False)),
                ('auto_now_add', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('model_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.modelfield')),
            ],
            options={
                'verbose_name': 'Date Field Config',
                'verbose_name_plural': 'Date Field Configs',
                'db_table': 'DateFieldConfig',
            },
        ),
        migrations.CreateModel(
            name='CharFieldConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_length', models.IntegerField()),
                ('regex_pattern', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('model_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.modelfield')),
            ],
            options={
                'verbose_name': 'Char Field Config',
                'verbose_name_plural': 'Char Field Configs',
                'db_table': 'CharFieldConfig',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='projects',
            field=models.ManyToManyField(through='core.Maintenance', to='core.Project'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
