# Generated by Django 3.2.16 on 2023-02-02 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_resetpasswordtoken_verificationtoken'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='modelfield',
            unique_together={('name', 'project_model')},
        ),
        migrations.AlterUniqueTogether(
            name='project',
            unique_together={('name', 'customer')},
        ),
        migrations.AlterUniqueTogether(
            name='projectmodel',
            unique_together={('name', 'project')},
        ),
    ]
