# Generated by Django 3.2.17 on 2023-02-04 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20230203_1832'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resetpasswordtoken',
            options={'verbose_name': 'Reset Password Token', 'verbose_name_plural': 'Reset Password Tokens'},
        ),
        migrations.AlterModelOptions(
            name='verificationtoken',
            options={'verbose_name': 'Verification Token', 'verbose_name_plural': 'Verification Tokens'},
        ),
        migrations.AlterModelTable(
            name='resetpasswordtoken',
            table='ResetPasswordToken',
        ),
        migrations.AlterModelTable(
            name='verificationtoken',
            table='VerificationToken',
        ),
    ]
