# Generated by Django 3.2.18 on 2023-02-18 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20230203_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelfield',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
