# Generated by Django 3.2.18 on 2023-03-15 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_modelfield_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateFieldType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Date Field Type',
                'verbose_name_plural': 'Date Field Types',
                'db_table': 'DateFieldType',
            },
        ),
        migrations.CreateModel(
            name='InputType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='datefieldconfig',
            name='type',
        ),
        migrations.RemoveField(
            model_name='filefieldconfig',
            name='content_types',
        ),
        migrations.RemoveField(
            model_name='filefieldconfig',
            name='max_upload_size',
        ),
        migrations.RemoveField(
            model_name='foreignkeyfieldconfig',
            name='relation_type',
        ),
        migrations.AddField(
            model_name='filefieldconfig',
            name='max_bytes_upload_size',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='foreignkeyfieldconfig',
            name='model_field_relation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='model_field_relation', to='core.modelfield'),
        ),
        migrations.AlterField(
            model_name='charfieldconfig',
            name='regex_pattern',
            field=models.CharField(default='.*', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='foreignkeyfieldconfig',
            name='model_field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_field', to='core.modelfield'),
        ),
        migrations.DeleteModel(
            name='UploadSize',
        ),
        migrations.AddField(
            model_name='datefieldconfig',
            name='date_field_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.datefieldtype'),
        ),
        migrations.AddField(
            model_name='foreignkeyfieldconfig',
            name='input_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.inputtype'),
        ),
    ]
