# Generated by Django 3.2.18 on 2023-03-16 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_user_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='filefieldconfig',
            name='content_types',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.contenttypes'),
            preserve_default=False,
        ),
    ]
